[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_post_source = '''
    let g:airline_theme = 'ubaryd'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_post_source = '''
    source ~/.vim/configs/nerdtree.vim
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = 'nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'jlanzarotta/bufexplorer'

[[plugins]]
repo = 'sjl/gundo.vim'
hook_post_source = '''
    source ~/.vim/configs/gundo.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'farmergreg/vim-lastplace'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_post_source = '''
    source ~/.vim/configs/fzf.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'breuckelen/vim-resize'
hook_source = '''
    let g:vim_resize_disable_auto_mappings = 1
    nnoremap  <left> :CmdResizeLeft<cr>
    nnoremap  <down> :CmdResizeDown<cr>
    nnoremap  <up> :CmdResizeUp<cr>
    nnoremap  <right> :CmdResizeRight<cr>
'''

[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_post_source = '''
    source ~/.vim/configs/tagbar.vim
'''

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'coderifous/textobj-word-column.vim'

[[plugins]]
repo = 'wellle/visual-split.vim'

[[plugins]]
repo = 'maxbrunsfeld/vim-yankstack'
hook_source = '''
    let g:yankstack_map_keys = 0
'''
hook_post_source = '''
    nmap <leader>p <Plug>yankstack_substitute_older_paste
    nmap <leader>P <Plug>yankstack_substitute_newer_paste
'''

[[plugins]]
repo = 'wellle/tmux-complete.vim'

[[plugins]]
repo = 'benmills/vimux'

[[plugins]]
repo = 'tpope/vim-obsession'

# syntax
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue', 'js']
hook_add = '''
autocmd FileType vue,javascript setlocal sts=2 sw=2 ts=2
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'avakhov/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
