set encoding=utf-8
scriptencoding utf-8

let mapleader=","
let g:mapleader=","

source ~/.vim/dein.vim

" ,, to repeat last fFtT in opposite direction (use ; to find next)
nnoremap <leader>; ,

" allow moving through windows via <C-j> instead of <C-W>j
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l

" common shortcuts
nmap <leader>w :w<CR>
nmap <leader>wq :wq<CR>
nmap <leader>q :q<CR>
nmap <leader>e :e <C-R>=expand('%:p:h') . '/'<cr><cr>
nmap <leader>v :vsp <C-R>=expand('%:p:h') . '/'<cr><cr>
nmap <leader>s :sp <C-R>=expand('%:p:h') . '/'<cr><cr>
command! W execute 'w !sudo tee %> /dev/null' | execute 'e!' | execute 'set noreadonly'

" tabs
nmap <C-w>p gT
nmap <C-w>n gt
nmap <C-w><C-p> gT
nmap <C-w><C-n> gt
nmap H gT
nmap L gt

" Use <C-/> to clear highlighting of hlsearch
nnoremap <silent> <leader>/ :nohlsearch<CR><C-L>

" easy (re)indenting in visual mode
vnoremap < <gv
vnoremap > >gv

" reselect pasted text
noremap <expr> g<c-v> '`[' . strpart(getregtype(), 0, 1) . '`]'

" tmux re-run last command
nmap <leader>r :call system('tmux select-pane -l; tmux send-keys up enter; tmux select-pane -l')<cr>
nmap <leader>c :call system('tmux select-pane -l; tmux send-keys c-c; tmux select-pane -l')<cr>

" auto-reload vimrc
autocmd! BufWritePost .vimrc source %

set background=dark
colorscheme molokai

set autoindent
set smartindent
set softtabstop=4
set tabstop=4
set shiftwidth=4
set expandtab
set nosmarttab
set shiftround
set textwidth=120

set list
let &listchars="tab:\u00bb\u00bb,trail:\u00b7,nbsp:\u00b7"

set nowrap
set linebreak
set breakindent
let &showbreak='↳  '
set breakindentopt=shift:2
set cpoptions+=n

set splitbelow
set splitright
set whichwrap+=<,>,h,l,[,]
set nostartofline
set formatoptions=roqnlj
set hidden
set modeline
set formatlistpat=^\\s*\\d\\+[.:)]\\s\\+\\\|^\\s*[-*]\\s\\+

set ruler
set number
set relativenumber
set cursorline
set scrolloff=3
set sidescrolloff=5
set laststatus=2
set virtualedit=block
set showmatch
set novisualbell
set noerrorbells

set hlsearch
set incsearch

set wildmenu
set wildmode=longest:full,full
set wildignore=*.pyc,*.pyo,*.o,*.obj,.*.swp

set history=1000
if has('persistent_undo')
    set undofile
    set undodir=~/.vim/undo
    if !isdirectory(&undodir)
        call mkdir(&undodir)
    endif
endif
