#!/bin/bash -e

brew_install() {
    if ! brew ls --versions $1; then
        brew install $@
    fi
}

install() {
    type brew &> /dev/null || {
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    }
    set +e
    brew_install coreutils
    brew_install binutils
    brew_install diffutils
    brew_install ed --with-default-names
    brew_install findutils --with-default-names
    brew_install gawk
    brew_install gnu-indent --with-default-names
    brew_install gnu-sed --with-default-names
    brew_install gnu-tar --with-default-names
    brew_install gnu-which --with-default-names
    brew_install gnutls
    brew_install grep --with-default-names
    brew_install gzip
    brew_install screen
    brew_install watch
    brew_install wget
    brew_install wdiff --with-gettext
    brew_install bash
    brew_install gpatch
    brew_install less
    brew_install git
    brew_install python
    brew_install rsync
    brew_install vim --override-system-vi
    brew_install macvim --override-system-vim --custom-system-icons
    brew_install zsh
    brew_install cscope
    brew_install ctags
    brew_install gnupg
    brew_install gpg-agent
    brew_install hub
    brew_install jq
    brew_install lastpass-cli
    brew_install oath-toolkit
    brew_install pstree
    brew_install tmux
    brew_install htop
    brew_install colordiff
    brew_install reattach-to-user-namespace
    brew cleanup
}

case "$OSTYPE" in
    darwin*)
        install
        ;;
    *) ;;
esac
