#!/bin/bash -e

install() {
    type gvm &> /dev/null || {
        export GVM_NO_UPDATE_PROFILE=1
        bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
        unset GVM_NO_UPDATE_PROFILE
    }
    [ -d ~/.gvim ] && {
        source ~/.vim/scripts/gvm
    }
    gvm install go1.7.3
    gvm install go1.8
}

install
