#!/bin/bash -e

install() {
    local url="https://github.com/getantibody/antibody/releases/download"
    local version=$(curl -s https://raw.githubusercontent.com/getantibody/homebrew-tap/master/Formula/antibody.rb | grep url | cut -f8 -d'/') || true
    version=v3.1.0
    test -z "$version" && {
        echo "unable to get antibody version"
        exit 1
    }
    mkdir -p bin
    cd bin
    curl -sL "$url/$version/antibody_$(uname -s)_$(uname -m).tar.gz" | tar -zx antibody
}

install
